name: "Hakyll"

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install Nix.
    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/lb41az54kzk6j12p81br4bczary7m145/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes

    # Pull from and push binaries to Cachix.
    - uses: cachix/cachix-action@v10
      with:
        name: splintah
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      # Allow Cachix to fail.
      continue-on-error: true

    # Build the site using Nix.
    - name: Build site
      run: |
        nix run .#build

    # Deploy the site to GitHub pages.
    - name: Deploy site
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
        publish_branch: master
